# Generated by Django 5.1.4 on 2024-12-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0003_alter_remisioncaso_firma_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisioncaso',
            name='nacimiento',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
